#!/usr/bin/env bash
# filters.sh - assemble combined filters file from ecosystem presets

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/core.sh"

# Where shipped ecosystem presets live (next to the repo config/)
PRESETS_DIR="${SCRIPT_DIR}/../config/ecosystems"
# User custom filters
CUSTOM_FILTERS="${CONFIG_DIR}/filters.custom"

build_filters() {
    ensure_dirs

    local tmp="${FILTERS_FILE}.tmp"

    {
        echo "# Auto-generated by openfilesync - do not edit directly"
        echo "# Edit ecosystem presets or ~/.config/openfilesync/filters.custom"
        echo ""

        # Combine all ecosystem preset files
        for preset in "${PRESETS_DIR}"/*.filters; do
            [[ -f "$preset" ]] || continue
            local name
            name="$(basename "$preset" .filters)"
            echo "# --- ${name} ---"
            cat "$preset"
            echo ""
        done

        # Append user custom filters if present
        if [[ -f "$CUSTOM_FILTERS" ]]; then
            echo "# --- custom ---"
            cat "$CUSTOM_FILTERS"
            echo ""
        fi
    } > "$tmp"

    mv "$tmp" "$FILTERS_FILE"
    log_info "Filters built: ${FILTERS_FILE}"
}
